name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          npm install -g github-pages  # Install GitHub Pages CLI
          npm run build  # Replace with your build command
          gh-pages -d dist  # Replace 'dist' with your build output directory

